haxis = gamepad_axis_value(0, gp_axislh);
vaxis = gamepad_axis_value(0, gp_axislv);
haxisreleased = (haxis == 0);
vaxisreleased = (vaxis == 0);
up = keyboard_check_pressed(vk_up) or gamepad_button_check_pressed(0,gp_padu);
down = keyboard_check_pressed(vk_down) or gamepad_button_check_pressed(0,gp_padd);
left = keyboard_check(vk_left) or gamepad_button_check(0,gp_padl);
right = keyboard_check(vk_right) or gamepad_button_check(0,gp_padr);
left2 = keyboard_check_pressed(vk_left) or gamepad_button_check_pressed(0,gp_padl);
right2 = keyboard_check_pressed(vk_right) or gamepad_button_check_pressed(0,gp_padr);
start = keyboard_check_pressed(vk_enter) or gamepad_button_check_pressed(0,gp_start);
z = keyboard_check_pressed(ord("Z")) or gamepad_button_check_pressed(0,gp_face1);
x_key = keyboard_check_pressed(ord("X")) or gamepad_button_check_pressed(0,gp_face2);
